name_com:
  api_username: "seothrone"
  api_token: "012447b6c68393cbe3ebaf9e3ce3bf81c844955a"

namecheap:
  api_user: "thronegamingdomains"
  api_key: "3df38c22e66a46e9a23dd63c16275e7a"
  client_ip: "80.85.111.50"

database:
  url: "sqlite:///domainz.db"
