
name_com:
  base_url: "https://api.name.com/v4"

namecheap:
  base_url: "https://api.namecheap.com/xml.response"

database:
  # The actual URL will be loaded from environment variables
  use_env_url: true
